# Created using wingetcreate 1.2.5.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.4.0.schema.json

PackageIdentifier: TL.TLLegacy
PackageVersion: 1.154.2.0
PackageLocale: en-US
Publisher: TL
PackageName: TL Legacy
License: hi,hi
ShortDescription: TLauncher Legacy, a Minecraft Launcher
ManifestType: defaultLocale
ManifestVersion: 1.4.0
